Get tutors
SW705E19/api pull request #18
Opened 2019-11-18 10:58 UTC by Fatdet

2019-11-18 11:01 UTC, andpaacoke requested changes

2019-11-18 11:01 UTC, andpaacoke commented on src/controllers/userController.ts
> +		const users: User[] = await userRepository
Skal du ikke hente deres TutorInfo med ud?

2019-11-18 11:01 UTC, andpaacoke commented on src/logging/users/users.log
> +{"name":"UserLogger","hostname":"DESKTOP-MAM25IS","pid":9760,"level":50,"err":{"message":"Could not find any entity of type \"User\" matching: \"0\"","name":"EntityNotFound","stack":"EntityNotFound:
no push log fil

2019-11-18 11:34 UTC, Tekrus requested changes

2019-11-18 11:34 UTC, Moesgaarda commented on src/controllers/userController.ts
> +	};
Det her conflicter også med #16 hvor jeg er ved at flytte al database interaktion ud i en service

2019-12-02 08:30 UTC, andpaacoke approved these changes

2019-12-02 08:30 UTC, Eduardsen approved these changes

2019-12-02 12:24 UTC, Tekrus approved these changes

2019-12-02 12:25 UTC, Tekrus requested changes
Warnings

2019-12-02 12:25 UTC, Tekrus approved these changes

2019-12-04 07:57 UTC, Tekrus requested changes
Ingen tests????????

nvm, bliver lavet i #33

2019-12-04 07:59 UTC, Tekrus approved these changes

2019-12-04 09:11 UTC, merged