Fixed getbyid for user to also fetch tutorInfo
SW705E19/api pull request #22
Opened 2019-11-21 12:39 UTC by andpaacoke

This is needed for https://github.com/SW705E19/frontend/pull/30 to work properly

2019-11-21 12:47 UTC, MathiasLybech approved these changes

2019-11-21 12:55 UTC, Tekrus requested changes

2019-11-21 12:55 UTC, Moesgaarda commented on src/services/userService.ts
> +			.getOne();
Skal man altid have tutorinfo med? Hvad hvis brugeren ikke er tutor?

2019-11-21 13:04 UTC, andpaacoke commented on src/services/userService.ts
> +			.getOne();
Så har de vel ikke en entry i TutorInfo table
men jo så skal vi vel tjekke om de har Tutor rollen på en eller anden måde? 🤔

2019-11-21 13:59 UTC, andpaacoke commented on src/services/userService.ts
> +			.getOne();
Har lavet et endpoint til at hente en tutorinfo ud i stedet ved at sende user id.
Derudover har jeg gjort sådan at den bør gemme user roles i token

2019-11-22 15:12 UTC, Tekrus submitted a review, later dismissed
Her kunne generelt godt være mindst en test, men snak lige med @jenspetur94 om det, han står til at skulle lave tests på userController i det her sprint

2019-11-22 15:12 UTC, Moesgaarda commented on src/controllers/userController.ts
> +			return res.status(404).send('Tutorinfo not found');
```suggestion
			return res.status(404).send('Tutor info not found');
```

2019-11-22 15:12 UTC, Moesgaarda commented on src/controllers/userController.ts
> +		const userId: string = req.params.id;
Det her må meget gerne være et number, det er refactored andre steder i APIen, da det er et number i modellen

2019-11-22 15:12 UTC, Moesgaarda commented on src/services/userService.ts
> +		const tutorInfoRepository: Repository<TutorInfo> = getRepository(TutorInfo);
Tag userId som number, lav konvertering inde i servicen

2019-11-25 08:38 UTC, Fatdet requested changes

2019-11-25 08:38 UTC, Fatdet commented on src/services/userService.ts
>  	static getById = async (id: string): Promise<User> => {
burde vel laves om til number eller så skal den anden være en string

2019-11-25 08:38 UTC, Fatdet commented on src/services/userService.ts
> +		const restutorInfo = await tutorInfoRepository
Skal vi have type på?

2019-11-25 08:47 UTC, Fatdet approved these changes

2019-11-25 08:58 UTC, merged