Service controller tests
SW705E19/api pull request #30
Opened 2019-11-27 11:54 UTC by andpaacoke

2019-11-27 12:08 UTC, Eduardsen commented on src/tests/serviceController.spec.ts
> +		sinon.stub(ServiceService, 'getDetailedById').resolves(mockServices[req.params.id - 1]);
er -1 nødvendig her?

2019-11-27 12:12 UTC, jenspetur94 requested changes

2019-11-27 12:12 UTC, jenspetur94 commented on src/controllers/serviceController.ts
> +			return res.status(409).send('Could not save service');
Det burde være en 400 istedet for en 409

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +		sinon.stub(ServiceService, 'getById').resolves(mockServices[req.params.id - 1]);
kunne du ikke bare have sat id i params til at at være 0 ?

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +		sinon.stub(ServiceService, 'getDetailedById').resolves(mockServices[req.params.id - 1]);
samme som før

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +		expect(res.statusCode).to.equal(404);
burde være 400

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should return status 404 on get service by id service not found', async () => {
burde være 400

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should return status 404 on get detailed service by id service not found', async () => {
burde være 400

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +		expect(res.statusCode).to.equal(404);
same

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should return status 404 on get service by category with wrong category', async () => {
400

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +		expect(res.statusCode).to.equal(404);
400

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +
burde du ikke lave en stub der thrower her ligesom du har gjort i andre tilfælde hvor den fejler ?

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +
burde du ikke have en stub der thrower her ?

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +
burde du ikke have en stub der thrower her ?

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should edit service and return status 204', async () => {
tror det skal være 200 og ikke 204

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should fail to edit service and return status 409', async () => {
tror det skal være 400 og ikke 409

2019-11-27 12:12 UTC, jenspetur94 commented on src/tests/serviceController.spec.ts
> +	it('should fail to delete service and return status 404', async () => {
burde være 400

2019-11-28 09:52 UTC, jenspetur94 approved these changes

2019-11-28 09:53 UTC, Eduardsen approved these changes

2019-11-28 11:45 UTC, merged