Recommender
SW705E19/api pull request #34
Opened 2019-12-04 14:10 UTC by Eduardsen

2019-12-05 10:35 UTC, Fatdet requested changes

2019-12-05 10:35 UTC, Fatdet commented on src/recommender/recommender.ts
> +	console.log(RMSE);
hallo?

2019-12-05 10:35 UTC, Fatdet commented on src/recommender/recommender.ts
> +	const numberOfFactors = 10;
Kan I ikke lige skrive hvorfor i bruger de her magic numbers?

2019-12-05 10:35 UTC, Fatdet commented on src/recommender/recommender.ts
> +	const numberOfFactors = 10;
eller i hvert fald bare at det er magic numbers

2019-12-09 08:07 UTC, MathiasLybech approved these changes

2019-12-09 08:07 UTC, Fatdet approved these changes

2019-12-09 08:50 UTC, merged