Editrole
SW705E19/api pull request #45
Opened 2019-12-13 10:50 UTC by Fatdet

2019-12-13 13:09 UTC, Tekrus requested changes
Branch % skal gerne op i grønt (80% covered) - generelt er test % faldet en del, det skal gerne op på samme niveau som før.

2019-12-13 13:09 UTC, Moesgaarda commented on src/controllers/userController.ts
> +			return res.status(400).send('email already in use');
Det kan du ikke vide, og det giver vel ikke mening i edit role?

2019-12-13 13:09 UTC, Moesgaarda commented on src/controllers/userController.ts
> +		return res.status(200).send();
Hvorfor har du en .send hvis du ikke sender? Burde du ikke sende useren eller rollerne tilbage?

2019-12-13 18:34 UTC, andpaacoke approved these changes

2019-12-14 08:53 UTC, Tekrus approved these changes

2019-12-14 09:44 UTC, merged