Crud category
SW705E19/api pull request #5
Opened 2019-10-24 06:44 UTC by Fatdet

Also changes database to postgres and modifies users to be able to have multiple roles

2019-10-24 06:49 UTC, Fatdet commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backend - category CRUD](https://trello.com/c/pDzbPMKg/38-backend-category-crud)

2019-10-24 06:53 UTC, Tekrus requested changes

2019-10-24 06:53 UTC, Moesgaarda commented on ormconfig.json
> +   "host": "134.209.249.61",
Det her skal nok ikke pushes til et offentligt repo

2019-10-24 06:53 UTC, Moesgaarda commented on src/logging/categories/category.log
> +{"name":"CategoryLogger","hostname":"DESKTOP-MAM25IS","pid":13696,"level":30,"msg":"Created: function bind() { [native code] }, category2","time":"2019-10-23T12:16:15.100Z","v":0}
Logs skal nok også tilføjes til git ignore

2019-10-24 06:53 UTC, Moesgaarda commented on src/middlewares/checkRole.ts
> +    if (rolefound) next();
er der en grund til at smide det i variable frem for bare at bruge [i] og [j]? Og er det ikke muligt at finde den her info med .some?

2019-10-24 06:53 UTC, Moesgaarda commented on src/controllers/categoryController.ts
> +            res.status(404).send("Category not found");
skal der ikke gøres noget med erroren? Enten logging eller andet

2019-10-24 06:53 UTC, Moesgaarda commented on src/controllers/categoryController.ts
> +            res.status(409).send("name already in use");
```suggestion
            res.status(409).send("Name already in use");
```

2019-10-24 09:01 UTC, Fatdet commented on ormconfig.json
> +   "host": "134.209.249.61",
Vil du så have mig til at tilføje den fil til gitignore så kan vi dele den privat?

2019-10-30 13:42 UTC, Tekrus approved these changes

2019-10-30 13:49 UTC, jenspetur94 approved these changes

2019-10-30 13:50 UTC, merged