Ratingidid
SW705E19/api pull request #50
Opened 2019-12-15 15:17 UTC by Fatdet

2019-12-15 16:09 UTC, Tekrus requested changes

2019-12-15 16:09 UTC, Tekrus commented on src/controllers/ratingController.ts
> +		if (existingRating != undefined) {
```suggestion
		if (existingRating !== undefined) {
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/controllers/ratingController.ts
> +				return res.status(400).send('Could not create rating');
```suggestion
				return res.status(400).send('Could not save rating');
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/controllers/ratingController.ts
> +			newRating;
Hvad gør den her linje?

2019-12-15 16:09 UTC, Moesgaarda commented on src/controllers/ratingController.ts
> +				return res.status(400).send('Could not create rating');
```suggestion
				return res.status(400).send('Could not save rating');
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/controllers/ratingController.ts
> +			return res.status(404).send('Could not find ratings');
```suggestion
			return res.status(404).send('Could not find rating');
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/routes/ratings.ts
> +router.post('/userIdServiceId', RatingController.getRatingByUserAndServiceId);
```suggestion
router.get('/userIdServiceId', RatingController.getRatingByUserAndServiceId);
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/tests/ratingController.spec.ts
> +	it('should find no rating and create a new rating, return 201', async () => {
```suggestion
	it('should create a new rating if one does not exist, return 201', async () => {
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/tests/ratingController.spec.ts
> +	it('should fail find a rating and fail to create a new rating and return status 400', async () => {
```suggestion
	it('should fail to find a rating and fail to create a new rating and return status 400', async () => {
```

2019-12-15 16:09 UTC, Moesgaarda commented on src/tests/ratingController.spec.ts
> +	});
Der kunne godt bruge en test på at den faktisk returner en rating

2019-12-15 16:09 UTC, Moesgaarda commented on src/services/ratingService.ts
> +	static getRatingByUserAndServiceId = async (userId: number, serviceId: number): Promise<Rating> => {
modsat linjefarm

2019-12-16 09:48 UTC, andpaacoke approved these changes

2019-12-16 09:48 UTC, Tekrus approved these changes

2019-12-16 10:14 UTC, merged